-- MySQL Script generated by MySQL Workbench
-- Mon Nov 19 01:21:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dreamland
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dreamland
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dreamland` DEFAULT CHARACTER SET utf8 ;
USE `dreamland` ;

-- -----------------------------------------------------
-- Table `dreamland`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dreamland`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(256) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `avatar` VARCHAR(32) NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dreamland`.`dream`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dreamland`.`dream` (
  `id_dream` INT NOT NULL,
  `id_user` INT NULL,
  `text` TEXT(65536) NOT NULL,
  `date` DATE NULL,
  `duration_minutes` INT NULL,
  PRIMARY KEY (`id_dream`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
